title: AI interaction log 
description: Website to publicly log my interactions with public AI agents, for transparency and attribution. Also disclose ethical principles I intend to follow in these interactions.
theme: just-the-docs
# remote_theme: just-the-docs/just-the-docs

url: https://garcias.github.io/ailog

aux_links:
  Repository: https://github.com/garcias/ailog

heading_anchors: true

callouts:
  prompt:
    title: Prompt
    color: blue
  response:
    title: Response
    color: yellow

